version: '2'
services:
  saiku:
    # build it yourself
    #build:
    #  context: https://github.com/gaerfield/saiku.git
    # or use prebuilt image
    image: gaerfield/saiku
    ports:
      - 8080
    volumes:
      - ./config/saiku_license.lic:/saiku_license.lic
      - ./config/cubes:/additionalCubes
      - ./config/bootstrapScripts:/docker-entrypoint-initdb.d
      - ./data/saiku:/saiku/data/
